{% set version = "0.6.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-profilemodel
  version: {{ version|replace("-", "_") }}

source:
  fn: profileModel_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/profileModel_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/profileModel/profileModel_{{ version }}.tar.gz

  sha256: a829ceec29c817d6d15947b818e28f9cf5a188a231b9b5d0a75018388887087b

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('profileModel')"  # [not win]
    - "\"%R%\" -e \"library('profileModel')\""  # [win]

about:
  home: http://www.ucl.ac.uk/~ucakiko/index.html
  license: GPL 2.0
  summary: profileModel provides tools that can be used to calculate, evaluate, plot and use
    for inference the profiles of *arbitrary* inference functions for *arbitrary* 'glm'-like
    fitted models with linear predictors.
  license_family: GPL

extra:
  recipe-maintainers:
    - dpryan79
    - johanneskoester
    - bgruening
