# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "oHaiwpNwnEso6659H/z7nYcYe3TeezOSq1JZ3j8nmlIQti00Vo7fbRaJslBLSKRMzWj86A4GHFWpr4C4mp+HEt5bS+alLqfQVu+HS90mNuK4BavUxf6NswpWpAQSYp6Oj3Lk5BuGBIP0w6pKb71vITZ3DAEYSFKqxiZRo+QJ3Pq3VpOBQeTS63/j/yqwJ/hwXPqr5a9nZNavCgBeyMFok7XUaDnNjX5uLYCcCFMLn9y5MhCWuvLAmUJGaU0dx+GsjF7UJst5PTQPbv46xFSZ1RRiNL2eDH5UidjG7uLhX91mQpbMzFSl+TbU3QLlxX3uQ1rlvOG0ktAHN79zhqBh2VVJU932yzzDq1wDnQy+CQ1TURMF7ph+xCHz+9vZHBPCaTp3OakecbqTmE//pwrluCOClf/sVV8fgQ4kLYYanCt3AJI56F+RDx4R4uROT8fTX2n2c4yvskS64Ako3/LoJ6hZO6xFRbvs6jgKR+5U6Hgkg5jl3cowzGJjFh6Lhbabh+TRUOY9FQMrpdRFINgIvpoVwq/MgjKDVUAEIxb29o76XoWYHIHEO3T1NejgVyVHn92l43KKsYbtP9P73X4KN4uf372iWwlJ1Q0k8oxxt1mtI1dlD3B+TV0rBoo6owrlOqB7srayS7QLH2Y26MkaYZnOGxh8FlWi+fitqoSX8oU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
