appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: oHaiwpNwnEso6659H/z7nYcYe3TeezOSq1JZ3j8nmlIQti00Vo7fbRaJslBLSKRMzWj86A4GHFWpr4C4mp+HEt5bS+alLqfQVu+HS90mNuK4BavUxf6NswpWpAQSYp6Oj3Lk5BuGBIP0w6pKb71vITZ3DAEYSFKqxiZRo+QJ3Pq3VpOBQeTS63/j/yqwJ/hwXPqr5a9nZNavCgBeyMFok7XUaDnNjX5uLYCcCFMLn9y5MhCWuvLAmUJGaU0dx+GsjF7UJst5PTQPbv46xFSZ1RRiNL2eDH5UidjG7uLhX91mQpbMzFSl+TbU3QLlxX3uQ1rlvOG0ktAHN79zhqBh2VVJU932yzzDq1wDnQy+CQ1TURMF7ph+xCHz+9vZHBPCaTp3OakecbqTmE//pwrluCOClf/sVV8fgQ4kLYYanCt3AJI56F+RDx4R4uROT8fTX2n2c4yvskS64Ako3/LoJ6hZO6xFRbvs6jgKR+5U6Hgkg5jl3cowzGJjFh6Lhbabh+TRUOY9FQMrpdRFINgIvpoVwq/MgjKDVUAEIxb29o76XoWYHIHEO3T1NejgVyVHn92l43KKsYbtP9P73X4KN4uf372iWwlJ1Q0k8oxxt1mtI1dlD3B+TV0rBoo6owrlOqB7srayS7QLH2Y26MkaYZnOGxh8FlWi+fitqoSX8oU=}
